services:

  postgres:
    image: dhi.io/postgres:18-alpine3.22-dev
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Root$1234
      POSTGRES_DB: Test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    networks:
      - default

  mongo:
    image: mongo:noble
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - default

  kafka:
    image: apache/kafka:3.9.2-rc1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:19092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - default
    volumes:
      - kafka_data:/var/lib/kafka/data
    
  frontend:
    container_name: frontend
    image: ayushsoni7777/micro-mart:frontend
    ports:
      - "80:80"
    networks:
      - default

  user-service:
    container_name: user-service
    image: ayushsoni7777/micro-mart:user-service
    environment:
      - .env
    ports:
      - "3001:3001"
    networks:
      - default

  product-service:
    container_name: product-service
    image: ayushsoni7777/micro-mart:product-service
    environment:
      - .env
    ports:
      - "3002:3002" 
    networks:
      - default

  order-service:
    container_name: order-service
    image: ayushsoni7777/micro-mart:order-service
    environment:
      - .env    
    ports:
      - "3003:3003" 
    networks:
      - default
  
  cart-service:
    container_name: cart-service
    image: ayushsoni7777/micro-mart:cart-service
    environment:
      - .env    
    ports:
      - "3004:3004" 
    networks: 
      - default
  
  inventory-service:
    container_name: inventory-service
    image: ayushsoni7777/micro-mart:inventory-service
    environment:
      - .env    
    ports:
      - "3005:3005" 
    networks: 
      - default
  
  reviews-service:
    container_name: reviews-service
    image: ayushsoni7777/micro-mart:reviews-service   
    environment:
      - .env
    ports:
      - "3006:3006" 
    networks: 
      - default
  
  payment-service:
    container_name: payment-service
    image: ayushsoni7777/micro-mart:payment-service   
    environment:
      - .env
    ports:
      - "3007:3007" 
    networks: 
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
  kafka_data: